//
// Created by incus on 2019-12-11.
//

#ifndef FFMPEGAUDIOPLAYER_COMMONS_H
#define FFMPEGAUDIOPLAYER_COMMONS_H

#include <stdlib.h>

#define SAMPLE_RATE 44100
#define BUFFER_SIZE 1024
#define MAX_SAMPLE_COUNT 512



#endif //FFMPEGAUDIOPLAYER_COMMONS_H
